mapbender_start:
    path: "/"
    defaults: { _controller: Mapbender\CoreBundle\Controller\WelcomeController::list}

mapbender_corebundle:
    resource: "@MapbenderCoreBundle/Controller/"
    type: attribute

mapbender_managerbundle:
    resource: "@MapbenderManagerBundle/Controller/"
    type: attribute

fom_userbundle:
    resource: "@FOMUserBundle/Controller"
    type: attribute

ows_corebundle:
    resource: "@OwsProxy3CoreBundle/Controller/"
    prefix: "/owsproxy"
    type: attribute
