parameters:
    applications:
        mapbender_user:
            title: Mapbender Demo
            screenshot: screenshot.png
            description: Full desktop demo application, showing all default Mapbender elements
            published: true
            persistentView: false
            template:  Mapbender\CoreBundle\Template\Fullscreen
            custom_css: |
              .toolBar.top {
                border-bottom: 3px solid #009ee0;
              }            
            regionProperties:
              - name: sidepane
                properties:
                  name: accordion
            layersets:
                Themen:
                    mapbender_users:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender Users
                        url: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml
                        version: 1.3.0
                        layers:
                            10: { name: Mapbender_User,    title : User, visible: true, legendurl: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mapbender_User&format=image/png&STYLE=default }
                            22: { name: Mapbender_Names,   title : Name, visible: true, queryable: true}
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 100
                        isBaseSource: false
                    overlay:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: NW Overlay für DOP
                        url: https://www.wms.nrw.de/geobasis/wms_nw_dop_overlay
                        version: 1.3.0
                        layers:
                            1: { name: WMS_NW_DOP_OVERLAY,    title : Overlay für DOP}
                        tiled: false
                        format: image/png
                        transparent: true
                        visible: false
                        opacity: 100
                        isBaseSource: false
                Hintergrundthema:                        
                    dop:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: NW DOP
                        url: https://www.wms.nrw.de/geobasis/wms_nw_dop
                        version: 1.3.0
                        layers:
                            1: { name: nw_dop_rgb,    title : WMS NW DOP RGB,  visible: true }
                        tiled: true
                        format: image/png
                        transparent: true
                        visible: false
                        opacity: 100
                        isBaseSource: true
                    osm:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            30: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: true
                        opacity: 100
                        isBaseSource: true
                overview:
                    osm_overview:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: 2o OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            40: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        tiled: false
                        format: image/png
                        transparent: true
                        visible: true
                        opacity: 100
                        isBaseSource: false                       
            elements:
                toolbar:
                    basesourceswitcher:
                        title: mb.core.basesourceswitcher.class.title
                        tooltip: mb.core.basesourceswitcher.class.title
                        class: Mapbender\CoreBundle\Element\BaseSourceSwitcher
                        display: group
                        target: map
                        instancesets:
                            1-basesourceswitcher:
                                title: OSM
                                group: Karten
                                instances:
                                    - osm
                            2-basesourceswitcher:
                                title: OSM + Overlay
                                group: Karten
                                instances: [osm, overlay]                                
                            3-basesourceswitcher:
                                title: DOP
                                group: Luftbilder
                                instances:
                                    - dop
                            4-basesourceswitcher:
                                title: DOP + Overlay
                                group: Luftbilder
                                instances:
                                    - dop
                                    - overlay
                            5-basesourceswitcher:
                                title: nur Overlay
                                group: Luftbilder
                                instances:
                                    - overlay
                            6-basesourceswitcher:
                                title: 'kein Hintergrund'
                                group: null
                                instances: []                    
                    fi-button:
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconInfoActive
                        label: true
                        target: featureinfo
                        group: featureinfo
                    legend-button:
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        target: legend
                        icon: iconLegend                                          
                    wmsloader-button:
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        target: wmsloader
                        icon: iconWms
                    linerulerButton:
                        title: mb.core.ruler.tag.measure
                        tooltip: mb.core.ruler.tag.line
                        class: Mapbender\CoreBundle\Element\Button
                        icon: icon-line-ruler
                        label: true
                        target: lineruler
                        group: rulers
                    arearulerButton:
                        title: mb.core.ruler.tag.measure
                        tooltip: mb.core.ruler.tag.area
                        class: Mapbender\CoreBundle\Element\Button
                        icon: icon-area-ruler
                        label: true
                        target: arearuler
                        group: rulers
                    gps-button:
                        class: Mapbender\CoreBundle\Element\GpsPosition
                        label: true
                        target: map                              
                    poiButton:
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconPoi
                        label: true
                        target: poi
                    print-button:
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        icon: iconPrint
                        target: printclient
                    imageexport-button:
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        icon: iconImageExport
                        target: imageexport                        
                    shareUrl:
                        class: Mapbender\CoreBundle\Element\ShareUrl
                        label: true
                    simplesearch:
                        title: mb.core.simplesearch.class.title
                        placeholder: 'Addresse eintragen...'
                        class: Mapbender\CoreBundle\Element\SimpleSearch
                        target: map
                        query_url: 'http://geodaten.metropoleruhr.de/suche?wt=json&indent=true&rows=10'                        
                        query_key: q
                        query_format: '%s'
                        token_regex: '[^a-zA-Z0-9äöüÄÖÜß]'
                        token_regex_in: '([a-zA-ZäöüÄÖÜß]{3,})'
                        token_regex_out: '$1*'
                        collection_path: response.docs
                        label_attribute: text
                        geom_attribute: utm32
                        sourceSrs: 'EPSG:25832'                        
                        geom_format: WKT
                        delay: 300
                        query_ws_replace: null
                        result:
                            buffer: 5
                            minscale: 100
                            maxscale: 1000
                            icon_url: '/bundles/mapbendercore/image/pin_red.png'
                            icon_offset: '-6,-32'
                content:
                    map:
                        class: Mapbender\CoreBundle\Element\Map
                        layersets: [Themen,Hintergrundthema]
                        srs: EPSG:25832
                        extents:
                            start: [361000,5619000,371150,5625000]
                            max: [-500000,4350000,1600000,6850000]
                        scales: [5000000,1000000,500000,100000,50000,25000,10000,7500,5000,2500,1000,500]
                        otherSrs: ["EPSG:25833","EPSG:31466","EPSG:31467","EPSG:3857","EPSG:4326"]
                    zoombar:
                        class: Mapbender\CoreBundle\Element\ZoomBar
                        target: map
                        anchor: right-top
                        draggable: false
                    legend:
                        class: Mapbender\CoreBundle\Element\Legend
                        target: map
                        elementType: dialog
                        autoOpen: false
                        showLayerTitle: true
                        showGroupedLayerTitle: true
                    featureinfo:
                        class: Mapbender\CoreBundle\Element\FeatureInfo
                        target: map
                        deactivateOnClose: false
                        onlyValid: true
                        displayType: tabs
                        autoActivate: false
                        printResult: true
                    wmsloader:
                        class: Mapbender\WmsBundle\Element\WmsLoader
                        target: map
                        autoOpen: false
                        defaultFormat: 'image/png'
                        defaultInfoFormat: 'text/html'
                        splitLayers: false
                    imageexport:
                        class: Mapbender\PrintBundle\Element\ImageExport
                        target: map
                    printclient:
                        class: Mapbender\PrintBundle\Element\PrintClient
                        target: map
                        templates:
                            - { template: a4portrait, label: A4 Portrait}
                            - { template: a4landscape, label: A4 Landscape}
                            - { template: a3portrait, label: A3 Portrait}
                            - { template: a3landscape, label: A3 Landscape}
                        legend_default_behaviour: false
                        optional_fields:
                            title:
                                label: Title              # label of the optional field
                                options:                  #
                                    required: true        # true or false
                    lineruler:
                        title: mb.core.ruler.tag.line
                        class: Mapbender\CoreBundle\Element\Ruler
                        target: map
                        type: line
                        strokeColor: 'rgba(0, 158, 224, 1)'
                    arearuler:
                        title: mb.core.ruler.tag.area
                        class: Mapbender\CoreBundle\Element\Ruler
                        target: map
                        type: area
                        fillColor: rgba(0, 158, 224, 0.5)
                        strokeColor: 'rgba(204, 210, 42, 1)'
                        fontColor: '#ffffff'
                        fontSize: 14
                        strokeWidth: 4
                        strokeWidthWhileDrawing: 3
                    scalebar:
                        class: Mapbender\CoreBundle\Element\ScaleBar
                        target: map
                        anchor: 'left-bottom'
                        maxWidth: 200
                        units: km
                    overview:
                        class: Mapbender\CoreBundle\Element\Overview
                        target: map
                        layerset: overview
                        anchor: 'right-bottom'
                        width: 300
                        height: 150
                        screenType: desktop
                    scaledisplay:
                        class: Mapbender\CoreBundle\Element\ScaleDisplay
                        target: map
                        anchor: right-top
                        scalePrefix: Scale
                        unitPrefix: true
                    poi:
                        class: Mapbender\CoreBundle\Element\POI
                        target: map
                        body: 'Bitte werfen Sie einen Blick auf diesen POI'
                        useMailto: false
                sidepane:
                    layertree:
                        class: Mapbender\CoreBundle\Element\Layertree
                        target: map
                        type: element
                        autoOpen: false
                        showBaseSource: true
                        layerRemove: true
                        menu: [opacity,zoomtolayer,metadata,removelayer]
                        hideNotToggleable: true
                        hideSelect: true
                        hideInfo: false
                        useTheme: true
                        themes:
                            -
                                id: Themen
                                title: 'Themen'
                                useTheme: true
                                opened: true
                                sourceVisibility: false
                                allSelected: false                        
                            -
                                id: Hintergrundthema
                                title: 'Hintergrundthema'
                                useTheme: true
                                opened: true
                                sourceVisibility: false
                                allSelected: false                                                          
                    viewmanager:
                        class: Mapbender\CoreBundle\Element\ViewManager
                        publicEntries: ro
                        privateEntries: true
                        allowAnonymousSave: false 
                        showDate: true        
                    sketch:
                        title: Skizzen Tool
                        class: Mapbender\CoreBundle\Element\Sketch
                        target: map
                        geometrytypes:
                            - point
                            - line
                            - polygon
                            - text
                            - rectangle
                            - circle
                        display_type: element
                        auto_activate: false
                        deactivate_on_close: false
                        colors: ["#FFFFFF","#cf003d","#ccd22a","#00837e","#009ee0","#000000"]
                        allow_custom_color: false       
                    coordinatesutility:
                        title: Koordinaten Utility
                        class: Mapbender\CoordinatesUtilityBundle\Element\CoordinatesUtility
                        target: map
                        srsList: []
                        addMapSrsList: true
                        zoomlevel: 6               
                    html-about-mapbender:
                        title: 'Über Mapbender'
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        classes: html-element-inline
                        content: "<p><b>Anwendungstitel:</b><br> {{ application.title }}</p><br><p>Mapbender is part of </p><p><a href=\"https://www.osgeo.org/projects/mapbender/\" target=\"_blank\"><img src=\"https://www.osgeo.org/wp-content/themes/roots/assets/img/logo-osgeo.svg\" alt=\"OSGeo Project\"  title=\"OSGeo Project\" width=\"100px\" /></a></p><p><br>Find out more about OSGeo at: <br/><a href=\"https://www.osgeo.org\" target=\"_blank\">https://www.osgeo.org</a><br/><a href=\"https://www.osgeo.org/projects/mapbender/\" target=\"_blank\">https://www.osgeo.org/projects/mapbender/</a>"
                footer:
                    activityindicator:
                        class: Mapbender\CoreBundle\Element\ActivityIndicator
                    coordinates:
                        class: Mapbender\CoreBundle\Element\CoordinatesDisplay
                        target: map
                        label: false
                        empty:  "x: - y: -"
                        prefix: "x: "
                        separator:  " y: "
                    scaleselector:
                        class: Mapbender\CoreBundle\Element\ScaleSelector
                        target: map
                    srs:
                        class: Mapbender\CoreBundle\Element\SrsSelector
                        target: map
                    applicationswitcher:
                        class: Mapbender\CoreBundle\Element\ApplicationSwitcher
                        applications: [mapbender_user, mapbender_user_basic]                      
                    copyrightButton:
                        title: © OpenStreetMap contributors
                        tooltip: © OpenStreetMap contributors
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        click: https://www.openstreetmap.org/copyright                       
                    HTML:
                        title: HTML-powered by Mapbender
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: '<span style="color: #009ee0; font-weight:bold">powered by Mapbender</span>'
                        classes: html-element-inline
                    about:
                        title: mb.core.aboutdialog.tag.about
                        tooltip: mb.core.aboutdialog.tag.about
                        label: false
                        class: Mapbender\CoreBundle\Element\AboutDialog   