security:
    encoders:
        FOM\UserBundle\Entity\User: sha512

    providers:
        main:
            entity:
                class: FOM\UserBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|components)/
            security: false

        login:
            pattern:  ^/user/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /user/login/check
                login_path: /user/login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /user/logout
                target: /
            # see https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.4.md#securitybundle
            logout_on_user_change: true

    access_control:
        - { path: ^/user/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manager,       roles: ROLE_USER }

