doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                path:     '%database_path%'
                user:     '%database_user%'
                password: '%database_password%'
                persistent: true
                charset:  UTF8
                logging: '%kernel.debug%'
                profiling: '%kernel.debug%'
            geodata_db:
                driver:   '%database2_driver%'
                host:     '%database2_host%'
                port:     '%database2_port%'
                dbname:   '%database2_name%'
                path:     '%database2_path%'
                user:     '%database2_user%'
                password: '%database2_password%'
                persistent: true
                charset:  UTF8
                logging: '%kernel.debug%'
                profiling: '%kernel.debug%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
