parameters:
    applications:
        mapbender_mobile:
            title: Mobile demo
            screenshot: screenshot.png
            description: Simple application using mobile template
            published: true
            template:  'Mapbender\MobileBundle\Template\Mobile'
            custom_css: |
                .toolBar.bottom {
                border-top: 2px solid #0066BA;
                }
                .toolBar {
                  color: #0066BA;
                }
                mobilePane .contentTitle {
                  flex: 0;
                  font-size: 142%;
                  border-bottom: solid 2px #0066BA;
                }
                .popup {
                border-color: #EEE9E9;
                border: 1px #EEE9E9;
                border-radius: 10px;
                }

                .popupHead {
                border-bottom: solid 1px #747577;
                margin: 0 20px 20px 20px;
                padding: 20px 0 10px 0;
                }

            layersets:
                main:
                    mapbender_users:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender Users
                        url: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml
                        version: 1.3.0
                        layers:
                            10: { name: Mapbender_User,    title : User, visible: true, legendurl: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mapbender_User&format=image/png&STYLE=default }
                            22: { name: Mapbender_Names,   title : Name, visible: true, queryable: true}
                        info_format: text/html
                        allowtoggle: false
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 100
                        isBaseSource: false
                    osm:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            30: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: true
                        opacity: 100
                        isBaseSource: true
                    osm_2:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo (with Opacity)
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            30: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: false
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 30
                        isBaseSource: true
            elements:
                footer:
                    # button parameters: action,activate,deactivate are ignored for elements at mobilePane
                    layertree-button:
                        title: mb.demoapps.themes
                        tooltip: Themes
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: icon-layer-tree
                        target: layertree

                    bss-button:
                        class: Mapbender\CoreBundle\Element\ControlButton
                        icon: iconMap
                        label: false
                        target: basesourceswitcher

                    gps-button:
                        class: Mapbender\CoreBundle\Element\GpsPosition
                        label: false
                        target: map
                        icon: iconGps
                        average: '1'
                        follow: false
                        centerOnFirstPosition: true
                        zoomToAccuracyOnFirstPosition: true

                    legend-button:
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconLegend
                        target: legend

                    imprint-button:
                        title: Imprint
                        tooltip: Imprint
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconInfoActive
                        target: imprint

                    help-button:
                        title: mb.core.aboutdialog.tag.help
                        tooltip: mb.core.aboutdialog.tag.help
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconHelp
                        target: help

                    about-mapbender-button:
                        title: mb.core.aboutdialog.tag.about
                        tooltip: mb.core.aboutdialog.tag.about
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconAbout
                        target: html-about-mapbender

                    shareUrl:
                        class: Mapbender\CoreBundle\Element\ShareUrl
                        label: false
                content:
                    map:
                        class: Mapbender\CoreBundle\Element\Map
                        layersets: [main]
                        srs: EPSG:3857
                        extents:
                            start: [772933.16,6566826.23,806786.66,6582317.62]
                            max: [-20037508.34278924,-20037508.34278924,20037508.34278924,20037508.34278924]
                        scales: [50000000,25000000,10000000,5000000,1000000,500000,100000,50000,25000,10000,7500,5000,2500,1000,500]
                        otherSrs: ["EPSG:25832","EPSG:25833","EPSG:31466","EPSG:31467","EPSG:4326"]
                    zoombar:
                        class: Mapbender\CoreBundle\Element\ZoomBar
                        target: map
                        components: ["rotation", "zoom_in_out", "zoom_max"]
                        anchor: right-bottom
                        draggable: false

                mobilePane:
                    layertree:
                        title: mb.demoapps.themes
                        class: Mapbender\CoreBundle\Element\Layertree
                        target: map
                        type: element
                        autoOpen: false
                        showBaseSource: false
                        menu: []

                    featureinfo:
                        class: Mapbender\CoreBundle\Element\FeatureInfo
                        target: map
                        deactivateOnClose: false
                        autoActivate: true
                        printResult: false
                        displayType: tabs
                        onlyValid: true

                    legend:
                        class: Mapbender\CoreBundle\Element\Legend
                        target: map
                        elementType: dialog
                        autoOpen: false
                        showLayerTitle: true
                        showGroupedLayerTitle: true

                    imprint:
                        title: Imprint
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: "<div style=\"color:#009ee0; font-weight:normal\" >powered by Mapbender.
                        Read more about Mapbender at the <a href=\"https://www.mapbender.org\" target=\"_blank\">Mapbender Project Page</a>.
                        </div>
                        <p><a href=\"https://mapbender.org\" target=\"_blank\">
                        <img src=\"../image/Mapbender-logo.png\" alt=\"Mapbender\"  title=\"Mapbender\" width=\"200px\" /></p>https://mapbender.org</a>
                        </p>
                        </p>"
                        classes: html-element-inline

                    help:
                        title: mb.core.aboutdialog.tag.help
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: "<p>Enjoy the Mapbender mobile Template.
                        Please note that not all elements can be used in the mobile application.</p>
                        <p>Please check the documentation</p>
                        <p><a href=\"https://doc.mapbender.org\" target=\"_blank\">
                        <img src=\"../image/Mapbender-logo.png\" alt=\"Mapbender\"  title=\"Mapbender\" width=\"200px\" /></p>
                        https://doc.mapbender.org</a>
                        </p>"
                        classes: html-element-inline

                    basesourceswitcher:
                        class: Mapbender\CoreBundle\Element\BaseSourceSwitcher
                        target: map
                        instancesets:
                            is1:
                                title: "OSM Demo (with opacity)"
                                group: ~
                                instances: [osm_2]
                            is2:
                                title: "OSM Demo"
                                group: ~
                                instances: [osm]

                    html-about-mapbender:
                        title: mb.core.aboutdialog.tag.about
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        classes: html-element-inline
                        content:  "<p>Learn more about Mapbender </p>
                        <p><a href=\"https://mapbender.org\" target=\"_blank\">
                        <img src=\"../image/Mapbender-logo.png\" alt=\"Mapbender\"  title=\"Mapbender\" width=\"200px\" /></p>https://mapbender.org</a>
                        </p>
                        <p>Mapbender is an</p>
                        <p><a href=\"https://www.osgeo.org/projects/mapbender/\" target=\"_blank\">
                        <p>
                        <img src=\"../bundles/mapbendercore/image/OSGeo_project.png\" alt=\"OSGeo Project\"  title=\"OSGeo Project\" width=\"150px\" /></a>
                        </p>
                        <p>
                        <a href=\"https://www.osgeo.org\" target=\"_blank\">https://www.osgeo.org</a>
                        </p>
                        </p>"